### ISSUE TITLE
List of potential topics to include for Wageningen 2021 talk

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/grass-gis-talks#2]
This is a brainstorming with myself and some bullet points we discussed with Vaclav, Anna and Martin. No specific order, some may already be in Vaclav and Anna's original presentation. What do you think?

- [x] GRASS general stuff as in https://veroandreo.github.io/grass_opengeohub2021/presentation.html
- [x] A slide about history + bday pic
- [x] Different interfaces (Python, QGIS, R, WPS)
- [x] Actinia
- [x] GSoC projects
- [x] New addons
- [x] add new splash screen somewhere
- [x] website + tutorials in different languages
- [x] docker images
- [x] lots of remote sensing/EO tools (see eg FOSDEM 2018 presentation)
- [x] time series 
- [x] band references
- [x] Sentinel toolbox (Guido?), Landsat, old good MODIS
- [x] Applications
- [x] Scientific applications (Google Scholar GRASS profile)
- [x] Community
- [x] Sponsoring - Donations at Opencollective

Importantly, we'll need to connect them with a storyline ;)

**Comment by HuidaeCho** [comment]
@veroandreo  Looks good. We could also list recent journal publications about GRASS in the Scientific applications section?

**Comment by ninsbl** [comment]
I would suggest to have GSoC slides earlier (before addons/use cases/examples).

**Comment by veroandreo** [comment]
Yes, I just merged all that could be merged, and now we need to re-organize/re-order

**Comment by metzm** [comment]
Since you are re-organizing the talk, how much sense does it make to create PR's?
Should we instead provide sniplets that you insert where you think they fit best?

**Comment by veroandreo** [comment]
> Since you are re-organizing the talk, how much sense does it make to create PR's?
> Should we instead provide sniplets that you insert where you think they fit best?

Yes, please, that's better at this point :)

Thanks a lot!

**Comment by metzm** [comment]
I suggest to move "GitHub-centered Software Development", "Code Quality", "Support" somewhere before "GRASS GIS 8".
After "GRASS GIS 8" maybe a slide alike "Exciting new features in GRASS 8"?

**Comment by veroandreo** [comment]
> "Support"

Thanks for the suggestions @metzm !

- The GitHub-centered Software Development slide is there because I thought of it more in terms of making a call to get involved and contribute... I haven't yet thought of a better title though. Would that make sense then?
- I agree the code quality was there before, but the items in that slide are about grass 8 improvements so what about an "Improved and more robust code quality checks" title ?
- I'll move support before grass 8, agreed :+1:

**Comment by veroandreo** [comment]
I believe we are pretty much done :)
Thanks everyone!!!
